import React from 'react';
import {Document, Page, StyleSheet, Text, View} from '@react-pdf/renderer';

// Create styles for PDF
const styles = StyleSheet.create({
    page: {
        padding: 30,
        backgroundColor: '#f8fafc' // slate-50
    },
    header: {
        fontSize: 24,
        marginBottom: 20,
        textAlign: 'center',
        color: '#22c55e' // green-500
    },
    sub_header: {
        fontSize: 20,
        marginBottom: 20,
        textAlign: 'center',
        color: '#22c55e' // green-500
    },
    table: {
        width: '100%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#22c55e', // gray-300
        borderRadius: 4
    },
    tableRow: {
        flexDirection: 'row'
    },
    tableHeader: {
        backgroundColor: '#22c55e', // green-500
        color: '#ffffff',
        padding: 8,
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
        borderRightWidth: 1,
        borderRightColor: '#d1d5db' // gray-300
    },
    tableCell: {
        padding: 4,
        fontSize: 8,
        textAlign: 'center',
        borderRightWidth: 1,
        borderRightColor: '#d1d5db', // gray-300
        borderBottomWidth: 1,
        borderBottomColor: '#d1d5db' // gray-300
    },
    footer: {
        marginTop: 20,
        fontSize: 10,
        textAlign: 'center',
        color: '#64748b' // slate-500
    }
});

// PDF Document Component
const PrayerTimesPDF = ({prayerTimes, month}) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>Darul Ihsan Berlin e.V </Text>
            <Text style={styles.sub_header}>Prayer Times for {month + ' ' + new Date().getFullYear()}</Text>

            <View style={styles.table}>
                {/* Table Header */}
                <View style={styles.tableRow}>
                    <Text style={[styles.tableHeader, {width: '21%'}]}>Date</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Fajr</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Sunrise</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Dhuhr</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Asr</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Maghrib</Text>
                    <Text style={[styles.tableHeader, {width: '15%'}]}>Isha</Text>
                </View>

                {/* Table Rows */}
                {prayerTimes.map((timeDay, index) => (
                    <View key={index} style={[styles.tableRow, {
                        backgroundColor: index % 2 === 0 ? '#ffffff' : '#f3f4f6' // white/gray-100
                    }]}>
                        {timeDay.map((time, index) => (<Text key={index}
                                                             style={index === 0 ? [styles.tableCell, {width: '21%'}] : [styles.tableCell, {width: '15%'}]}>{time}</Text>))}
                    </View>
                ))}
            </View>

            <Text style={styles.footer}>Generated by Prayer Times App</Text>
        </Page>
    </Document>
);

export default PrayerTimesPDF;